Applied statistics Lab to check for outliers

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load the CSV file into a DataFrame
df = pd.read_csv("D:\My Repositories\BTDS-FY_Files-Assignments\Python_\Assignments\Appiled Statistics\heights.csv")

# Display the first few rows of the DataFrame
df.head()

<>:6: SyntaxWarning: invalid escape sequence '\M'
<>:6: SyntaxWarning: invalid escape sequence '\M'
C:\Users\Admin\AppData\Local\Temp\ipykernel_764\2581144502.py:6: SyntaxWarning: invalid escape sequence '\M'
  df = pd.read_csv("D:\My Repositories\BTDS-FY_Files-Assignments\Python_\Assignments\Appiled Statistics\heights.csv")

   Name  Height
0     1    1.65
1     2    1.70
2     3    1.68
3     4    1.72
4     5    1.60

In [8]:
df.describe()

           Name     Height
count  20.00000  20.000000
mean   10.50000   1.868000
std     5.91608   0.875789
min     1.00000   0.300000
25%     5.75000   1.637500
50%    10.50000   1.685000
75%    15.25000   1.732500
max    20.00000   4.500000

In [9]:
df.mean()

Name      10.500
Height     1.868
dtype: float64

In [10]:
df.median()

Name      10.500
Height     1.685
dtype: float64

In [11]:
df.mode()

    Name  Height
0      1    0.30
1      2    1.60
2      3    1.61
3      4    1.62
4      5    1.63
5      6    1.64
6      7    1.65
7      8    1.66
8      9    1.67
9     10    1.68
10    11    1.69
11    12    1.70
12    13    1.71
13    14    1.72
14    15    1.73
15    16    1.74
16    17    1.75
17    18    1.76
18    19    4.00
19    20    4.50

In [16]:
min_threshold = df['Height'].min()
min_threshold

np.float64(0.3)

In [19]:
df[df['Height']!=min_threshold]

    Name  Height
0      1    1.65
1      2    1.70
2      3    1.68
3      4    1.72
4      5    1.60
5      6    1.75
6      7    1.62
7      8    1.69
8      9    1.64
9     10    1.71
10    11    1.67
11    12    1.73
12    13    1.66
13    14    1.61
14    15    1.74
15    16    1.63
16    17    1.76
17    18    4.00
18    19    4.50